services:
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - 3000:3000
    networks:
      - network_priv_3x03

  backend:
    container_name: backend
    image: backend
    networks:
      - network_priv_3x03

networks:
  network_priv_3x03:
    name: network_priv_3x03