pipeline {
    agent any
    tools {nodejs "Default"}

    stages {
        stage("Fetch") {
            steps {
                git branch: "testreport",
                    url: "https://github.com/IENORI/Cookies.git"
            }
        }
        stage("Install") {
            parallel {
                stage("Frontend") {
                    steps {
                        echo "This is from testpipeline branch"
                        dir('frontend') {
                            sh 'rm package-lock.json'
                            sh 'rm -rf node_modules'
                            sh 'npm install'
                        }
                    }
                }
                stage("Backend") {
                    steps {
                        dir('backend') {
                            sh 'rm package-lock.json'
                            sh 'rm -rf node_modules'
                            sh 'npm install'
                        }
                    }
                }
            }
        }
        stage("Test") {
            steps {
                dir('backend') {
                    sh 'npm test'
                }
            }
        }
    }
    post {
        always {
            junit './backend/*.xml'
        }
    }
}